# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'srcui/qoptirun.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(694, 532)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.layout_appspresets = QtWidgets.QHBoxLayout()
        self.layout_appspresets.setObjectName("layout_appspresets")
        self.programs_tabwidget = QtWidgets.QTabWidget(self.centralwidget)
        self.programs_tabwidget.setTabPosition(QtWidgets.QTabWidget.South)
        self.programs_tabwidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.programs_tabwidget.setDocumentMode(False)
        self.programs_tabwidget.setObjectName("programs_tabwidget")
        self.applications_tab = QtWidgets.QWidget()
        self.applications_tab.setObjectName("applications_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.applications_tab)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.applications_list = QtWidgets.QTreeWidget(self.applications_tab)
        self.applications_list.setRootIsDecorated(False)
        self.applications_list.setUniformRowHeights(True)
        self.applications_list.setItemsExpandable(False)
        self.applications_list.setExpandsOnDoubleClick(False)
        self.applications_list.setObjectName("applications_list")
        self.verticalLayout.addWidget(self.applications_list)
        self.programs_tabwidget.addTab(self.applications_tab, "")
        self.presets_tab = QtWidgets.QWidget()
        self.presets_tab.setObjectName("presets_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.presets_tab)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.presets_list = QtWidgets.QTreeWidget(self.presets_tab)
        self.presets_list.setAlternatingRowColors(True)
        self.presets_list.setRootIsDecorated(False)
        self.presets_list.setUniformRowHeights(True)
        self.presets_list.setItemsExpandable(False)
        self.presets_list.setExpandsOnDoubleClick(False)
        self.presets_list.setObjectName("presets_list")
        self.verticalLayout_2.addWidget(self.presets_list)
        self.programs_tabwidget.addTab(self.presets_tab, "")
        self.layout_appspresets.addWidget(self.programs_tabwidget)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.preset_save = QtWidgets.QPushButton(self.centralwidget)
        self.preset_save.setObjectName("preset_save")
        self.verticalLayout_3.addWidget(self.preset_save)
        self.preset_load = QtWidgets.QPushButton(self.centralwidget)
        self.preset_load.setObjectName("preset_load")
        self.verticalLayout_3.addWidget(self.preset_load)
        self.preset_delete = QtWidgets.QPushButton(self.centralwidget)
        self.preset_delete.setObjectName("preset_delete")
        self.verticalLayout_3.addWidget(self.preset_delete)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.layout_appspresets.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.layout_appspresets)
        self.layout_path = QtWidgets.QHBoxLayout()
        self.layout_path.setObjectName("layout_path")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.layout_path.addWidget(self.label)
        self.program_path = QtWidgets.QLineEdit(self.centralwidget)
        self.program_path.setObjectName("program_path")
        self.layout_path.addWidget(self.program_path)
        self.program_path_browse = QtWidgets.QPushButton(self.centralwidget)
        self.program_path_browse.setObjectName("program_path_browse")
        self.layout_path.addWidget(self.program_path_browse)
        self.verticalLayout_4.addLayout(self.layout_path)
        self.layout_args = QtWidgets.QHBoxLayout()
        self.layout_args.setObjectName("layout_args")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.layout_args.addWidget(self.label_4)
        self.program_args = QtWidgets.QLineEdit(self.centralwidget)
        self.program_args.setObjectName("program_args")
        self.layout_args.addWidget(self.program_args)
        self.verticalLayout_4.addLayout(self.layout_args)
        self.layout_optirun = QtWidgets.QHBoxLayout()
        self.layout_optirun.setObjectName("layout_optirun")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.layout_optirun.addWidget(self.label_2)
        self.optirun_bridge = QtWidgets.QComboBox(self.centralwidget)
        self.optirun_bridge.setObjectName("optirun_bridge")
        self.optirun_bridge.addItem("")
        self.optirun_bridge.addItem("")
        self.optirun_bridge.addItem("")
        self.optirun_bridge.addItem("")
        self.layout_optirun.addWidget(self.optirun_bridge)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.layout_optirun.addWidget(self.label_3)
        self.optirun_vglcompress = QtWidgets.QComboBox(self.centralwidget)
        self.optirun_vglcompress.setObjectName("optirun_vglcompress")
        self.optirun_vglcompress.addItem("")
        self.optirun_vglcompress.addItem("")
        self.optirun_vglcompress.addItem("")
        self.optirun_vglcompress.addItem("")
        self.optirun_vglcompress.addItem("")
        self.optirun_vglcompress.addItem("")
        self.layout_optirun.addWidget(self.optirun_vglcompress)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.layout_optirun.addWidget(self.label_5)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_optirun.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.layout_optirun)
        self.layout_progctl = QtWidgets.QHBoxLayout()
        self.layout_progctl.setObjectName("layout_progctl")
        self.program_waitforclose = QtWidgets.QCheckBox(self.centralwidget)
        self.program_waitforclose.setEnabled(False)
        self.program_waitforclose.setObjectName("program_waitforclose")
        self.layout_progctl.addWidget(self.program_waitforclose)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_progctl.addItem(spacerItem2)
        self.program_run = QtWidgets.QPushButton(self.centralwidget)
        self.program_run.setObjectName("program_run")
        self.layout_progctl.addWidget(self.program_run)
        self.program_terminate = QtWidgets.QToolButton(self.centralwidget)
        self.program_terminate.setEnabled(False)
        self.program_terminate.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.program_terminate.setArrowType(QtCore.Qt.NoArrow)
        self.program_terminate.setObjectName("program_terminate")
        self.layout_progctl.addWidget(self.program_terminate)
        self.verticalLayout_4.addLayout(self.layout_progctl)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.programs_tabwidget.setCurrentIndex(0)
        self.optirun_bridge.setCurrentIndex(0)
        self.applications_list.itemSelectionChanged.connect(MainWindow.appListSelect)
        self.presets_list.itemSelectionChanged.connect(MainWindow.presetListSelect)
        self.program_run.clicked.connect(MainWindow.runProgram)
        self.program_terminate.clicked.connect(MainWindow.termProgram)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QOptirun"))
        self.applications_list.setSortingEnabled(True)
        self.applications_list.headerItem().setText(0, _translate("MainWindow", "Name"))
        self.applications_list.headerItem().setText(1, _translate("MainWindow", "Executable"))
        self.applications_list.headerItem().setText(2, _translate("MainWindow", "Arguments"))
        self.applications_list.headerItem().setText(3, _translate("MainWindow", "Bridge"))
        self.applications_list.headerItem().setText(4, _translate("MainWindow", "VGLCompress"))
        self.applications_list.headerItem().setText(5, _translate("MainWindow", "WaitForClose"))
        self.programs_tabwidget.setTabText(self.programs_tabwidget.indexOf(self.applications_tab), _translate("MainWindow", "Applications"))
        self.presets_list.setSortingEnabled(True)
        self.presets_list.headerItem().setText(0, _translate("MainWindow", "Name"))
        self.presets_list.headerItem().setText(1, _translate("MainWindow", "Executable"))
        self.presets_list.headerItem().setText(2, _translate("MainWindow", "Arguments"))
        self.presets_list.headerItem().setText(3, _translate("MainWindow", "Bridge"))
        self.presets_list.headerItem().setText(4, _translate("MainWindow", "VGLCompress"))
        self.presets_list.headerItem().setText(5, _translate("MainWindow", "WaitForClose"))
        self.programs_tabwidget.setTabText(self.programs_tabwidget.indexOf(self.presets_tab), _translate("MainWindow", "Presets"))
        self.preset_save.setText(_translate("MainWindow", "Save"))
        self.preset_load.setText(_translate("MainWindow", "Load"))
        self.preset_delete.setText(_translate("MainWindow", "Delete"))
        self.label.setText(_translate("MainWindow", "Program Path"))
        self.program_path_browse.setText(_translate("MainWindow", "Browse"))
        self.label_4.setText(_translate("MainWindow", "Arguments"))
        self.label_2.setText(_translate("MainWindow", "Bridge"))
        self.optirun_bridge.setItemText(0, _translate("MainWindow", "Default"))
        self.optirun_bridge.setItemText(1, _translate("MainWindow", "None"))
        self.optirun_bridge.setItemText(2, _translate("MainWindow", "VirtualGL"))
        self.optirun_bridge.setItemText(3, _translate("MainWindow", "Primus"))
        self.label_3.setText(_translate("MainWindow", "VGL Compress"))
        self.optirun_vglcompress.setItemText(0, _translate("MainWindow", "Default"))
        self.optirun_vglcompress.setItemText(1, _translate("MainWindow", "Proxy"))
        self.optirun_vglcompress.setItemText(2, _translate("MainWindow", "RGB"))
        self.optirun_vglcompress.setItemText(3, _translate("MainWindow", "YUV"))
        self.optirun_vglcompress.setItemText(4, _translate("MainWindow", "XV"))
        self.optirun_vglcompress.setItemText(5, _translate("MainWindow", "JPEG"))
        self.label_5.setText(_translate("MainWindow", "Compression only works with VirtualGL"))
        self.program_waitforclose.setText(_translate("MainWindow", "Wait For Close"))
        self.program_run.setText(_translate("MainWindow", "Run"))
        self.program_terminate.setText(_translate("MainWindow", "Terminate"))

